CREATE TABLE ATHLETE (
  USERNAME                  VARCHAR(255) PRIMARY KEY,
  CURRENT_CURRENCY          BIGINT,
  TOTAL_CURRENCY            BIGINT,
  MAXIMUM_SPENT             BIGINT,
  TOTAL_CODES_FOUND         BIGINT
);
