CREATE SEQUENCE QR_CODE_ID_SEQ
  MINVALUE 0
  MAXVALUE 9223372036854775807
  CACHE 10;
CREATE TABLE QR_CODE (
  ID                       BIGINT PRIMARY KEY,
  ATHLETE_USERNAME          VARCHAR(255),
  CODE                      VARCHAR(255),
  CONSTRAINT FK_QR_CODE_ID FOREIGN KEY (ATHLETE_USERNAME) REFERENCES ATHLETE
);
