CREATE TABLE "ATHLETE" (
  "USERNAME"                  VARCHAR2(255 CHAR) PRIMARY KEY,
  "CURRENT_CURRENCY"          NUMBER(19),
  "TOTAL_CURRENCY"            NUMBER(19),
  "MAXIMUM_SPENT"             NUMBER(19),
  "TOTAL_CODES_FOUND"         NUMBER(19)
);