CREATE SEQUENCE "QR_CODE_ID_SEQ"
  MINVALUE 0
  MAXVALUE 9223372036854775807
  CACHE 10;
CREATE TABLE "QR_CODE" (
  "ID"                        NUMBER(19) PRIMARY KEY,
  "ATHLETE_ID"                NUMBER(19),
  "CODE"                      NUMBER(19),
  CONSTRAINT "FK_QR_CODE_ID" FOREIGN KEY ("ATHLETE_ID") REFERENCES "ATHLETE"
);